version: "3"
services:
  consul:
    image: consul:1.6.4
    container_name: consul
    ports:
      - 8500:8500
    command: "agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1 -ui"
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    hostname: "rabbit"
    ports:
      - 16672:15672
      - 6672:5672
    labels:
      NAME: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  mysql:
    image: mysql:5.7
    container_name: mysql-57
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testdb
    volumes:
      - /mysql_data:/var/lib/mysql
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - /mongo_data:/data/db
  terabizcloud-config: 
    image: terabizcloud-config:config
    container_name: terabizcloud-config
    ports:
      - 8080:8080
  terabizcloud-auth:
    image: terabizcloud-auth:auth
    container_name: terabizcloud-auth
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - CONFIG_SERVER_HOST=terabizcloud-config
      - CONFIG_SERVER_PORT=8080
    ports:
      - 8081:8081
    depends_on:
        - consul
        - terabizcloud-config
  terabizcloud-mysql:
    image: terabizcloud-mysql:mysql
    container_name: terabizcloud-mysql
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - CONFIG_SERVER_HOST=terabizcloud-config
      - CONFIG_SERVER_PORT=8080
      - MYSQL_HOST=mysql-57
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
    ports:
      - 8082:8082
    depends_on:
        - consul
        - mysql
        - rabbitmq
        - terabizcloud-config
        - terabizcloud-auth
  terabizcloud-mongo:
    image: terabizcloud-mongo:mongo
    container_name: terabizcloud-mongo
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - CONFIG_SERVER_HOST=terabizcloud-config
      - CONFIG_SERVER_PORT=8080
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=root
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
    ports:
      - 8083:8083
    depends_on:
        - consul
        - mongo
        - rabbitmq
        - terabizcloud-config
        - terabizcloud-auth

